apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flatris
  namespace: flatris
spec:
  interval: 5m
  url: oci://ghcr.io/netology-diploma
  secretRef:
    name: ghcr-auth
