apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flatris
  namespace: flatris
spec:
  releaseName: flatris
  interval: 15m
  chart:
    spec:
      chart: flatris
      sourceRef:
        kind: HelmRepository
        name: flatris
        namespace: flatris
      version: 0.2.2
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: flatris.tasenko.ru
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: letsencrypt-prod
          hosts:
            - flatris.tasenko.ru
