name: Publish Helm Chart to YCR

on:
  push:
    branches: [ "helm-chart-update" ]

env:
  HELM_VERSION_TO_INSTALL: 3.8.0 # version of HEL to install
  GCR_IMAGE: ghcr.io/${{ github.repository_owner }}/flatris

jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install helm
        uses: Azure/setup-helm@v1
        with:
          # Version of helm
          version: ${{ env.HELM_VERSION_TO_INSTALL }} # default is latest

      - name: Login to gcr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ github.repository_owner }} --password-stdin

      - name: Save helm chart to local registry
        run: |
          helm save ${{ github.workspace }}/src/azure-vote-helm-chart/ ${{ env.GCR_IMAGE }}:${{ github.sha }}

      - name: Publish chart to gcr
        run: |
          helm push ${{ env.GCR_IMAGE }}:${{ github.sha }}
